version: '3.9'
services:
  redis:
    image: redis
    container_name: redis    
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf      

  k6:
    image: loadimpact/k6
    container_name: k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    environment:
      - INFLUXDB_DB=K6
    #  - INFLUXDB_USER=k6
    #  - INFLUXDB_ADMIN_ENABLED=true
    #  - INFLUXDB_ADMIN_USER=admin
    #  - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      #- ./influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089/udp"    

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./data/grafana:/root/ ./var/lib/grafana/     
    user: "472"  



